
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.lang.Math.toIntExact;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LUCKY
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        selectPinjam();
        selectBuku();
        selectAnggota();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btPrint = new javax.swing.JButton();
        btHitung = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Pinjam = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        Judul = new javax.swing.JTextField();
        Kembali = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbData = new javax.swing.JTable();
        Struk = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        Biaya = new javax.swing.JTextField();
        btSave = new javax.swing.JButton();
        btClear = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbBuku = new javax.swing.JTable();
        PrintBuku = new javax.swing.JButton();
        DeleteBuku = new javax.swing.JButton();
        Tahun = new javax.swing.JTextField();
        Kode = new javax.swing.JTextField();
        JudulBuku = new javax.swing.JTextField();
        Penulis = new javax.swing.JTextField();
        cbBuku = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ClearBuku = new javax.swing.JButton();
        SaveBuku = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        cbCariBuku = new javax.swing.JComboBox<>();
        SearchBuku = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbAnggota = new javax.swing.JTable();
        PrintAnggota = new javax.swing.JButton();
        DeleteAnggota = new javax.swing.JButton();
        Nis = new javax.swing.JTextField();
        NamaAnggota = new javax.swing.JTextField();
        Kelas = new javax.swing.JTextField();
        Telp = new javax.swing.JTextField();
        vjak = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        dytk = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        rbLaki = new javax.swing.JRadioButton();
        rbPerempuan = new javax.swing.JRadioButton();
        ClearAnggota = new javax.swing.JButton();
        SaveAnggota = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btPrint1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perpustakaan Telkom School");
        setBackground(new java.awt.Color(162, 5, 20));
        setMinimumSize(new java.awt.Dimension(760, 580));
        setPreferredSize(new java.awt.Dimension(760, 580));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama Peminjam");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        btPrint.setText("PRINT");
        btPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrintActionPerformed(evt);
            }
        });
        jPanel1.add(btPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 110, 30));

        btHitung.setText("HITUNG");
        btHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHitungActionPerformed(evt);
            }
        });
        jPanel1.add(btHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 110, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nomor Struk");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tanggal Pinjam");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        Pinjam.setBackground(new java.awt.Color(209, 37, 37));
        jPanel1.add(Pinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 140, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Judul Buku");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));
        jPanel1.add(Judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 140, -1));

        Kembali.setBackground(new java.awt.Color(209, 37, 37));
        jPanel1.add(Kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 140, -1));

        tbData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NoStruk", "Judul Buku", "Nama", "TanggalPinjam", "TanggalKembali", "Biaya"
            }
        ));
        tbData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbData);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 700, 170));
        jPanel1.add(Struk, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 140, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tanggal Kembali");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Biaya");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, -1));
        jPanel1.add(Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 140, -1));

        Biaya.setEditable(false);
        jPanel1.add(Biaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 140, -1));

        btSave.setText("SAVE");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 110, 30));

        btClear.setText("CLEAR");
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });
        jPanel1.add(btClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 110, 30));

        btDelete.setText("DELETE");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 110, 30));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Biaya < 3 hari = Rp. 0 \t\t|| Biaya > 3 hari = Rp.500/hari\nPastikan untuk cek biaya sebelum memasukkan data peminjaman");
        jScrollPane4.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 530, 50));

        jLabel15.setFont(new java.awt.Font("Amarillo", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Peminjaman Buku Perpustakaan");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 380, 40));

        jPanel6.setBackground(new java.awt.Color(209, 37, 37));
        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 410));

        jTabbedPane1.addTab("Data Peminjaman", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Buku", "Judul Buku", "Penulis Buku", "Kategori", "Tahun Rilis"
            }
        ));
        tbBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbBukuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbBuku);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 700, 160));

        PrintBuku.setText("PRINT");
        PrintBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintBukuActionPerformed(evt);
            }
        });
        jPanel2.add(PrintBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 110, 30));

        DeleteBuku.setText("DELETE");
        DeleteBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBukuActionPerformed(evt);
            }
        });
        jPanel2.add(DeleteBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 110, 30));

        Tahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TahunActionPerformed(evt);
            }
        });
        jPanel2.add(Tahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 140, -1));

        Kode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KodeActionPerformed(evt);
            }
        });
        jPanel2.add(Kode, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 140, -1));

        JudulBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JudulBukuActionPerformed(evt);
            }
        });
        jPanel2.add(JudulBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 140, -1));

        Penulis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenulisActionPerformed(evt);
            }
        });
        jPanel2.add(Penulis, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 140, -1));

        cbBuku.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pelajaran", "Novel", "Referensi", "Tips" }));
        jPanel2.add(cbBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 140, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tahun Rilis");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Kode Buku");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Judul Buku");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Penulis");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        ClearBuku.setText("CLEAR");
        ClearBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBukuActionPerformed(evt);
            }
        });
        jPanel2.add(ClearBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 110, 30));

        SaveBuku.setText("SAVE");
        SaveBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBukuActionPerformed(evt);
            }
        });
        jPanel2.add(SaveBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 110, 30));

        jLabel16.setFont(new java.awt.Font("Amarillo", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Koleksi Buku Perpustakaan");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 320, 40));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Cari Buku Berdasarkan Kategori"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Kategori Buku");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        cbCariBuku.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pelajaran", "Novel", "Referensi", "Tips" }));
        jPanel4.add(cbCariBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, -1));

        SearchBuku.setText("SEARCH");
        SearchBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBukuActionPerformed(evt);
            }
        });
        jPanel4.add(SearchBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 110, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 170, 120));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Kategori Buku");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        jPanel7.setBackground(new java.awt.Color(209, 37, 37));
        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 410));

        jTabbedPane1.addTab("Data Buku", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbAnggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIS", "Nama", "Kelas", "Jenis Kelamin", "No Hp"
            }
        ));
        tbAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAnggotaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbAnggota);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 700, 160));

        PrintAnggota.setText("PRINT");
        PrintAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintAnggotaActionPerformed(evt);
            }
        });
        jPanel3.add(PrintAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 110, 30));

        DeleteAnggota.setText("DELETE");
        DeleteAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteAnggotaActionPerformed(evt);
            }
        });
        jPanel3.add(DeleteAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 110, 30));

        Nis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NisActionPerformed(evt);
            }
        });
        jPanel3.add(Nis, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 140, -1));

        NamaAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaAnggotaActionPerformed(evt);
            }
        });
        jPanel3.add(NamaAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 140, -1));

        Kelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KelasActionPerformed(evt);
            }
        });
        jPanel3.add(Kelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 140, -1));

        Telp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelpActionPerformed(evt);
            }
        });
        jPanel3.add(Telp, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 140, -1));

        vjak.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        vjak.setForeground(new java.awt.Color(255, 255, 255));
        vjak.setText("NIS");
        jPanel3.add(vjak, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nama");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        dytk.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dytk.setForeground(new java.awt.Color(255, 255, 255));
        dytk.setText("Kelas");
        jPanel3.add(dytk, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Jenis Kelamin");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("No Hp");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        buttonGroup1.add(rbLaki);
        rbLaki.setForeground(new java.awt.Color(255, 255, 255));
        rbLaki.setText("Laki - Laki");
        jPanel3.add(rbLaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        buttonGroup1.add(rbPerempuan);
        rbPerempuan.setForeground(new java.awt.Color(255, 255, 255));
        rbPerempuan.setText("Perempuan");
        jPanel3.add(rbPerempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        ClearAnggota.setText("CLEAR");
        ClearAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearAnggotaActionPerformed(evt);
            }
        });
        jPanel3.add(ClearAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 110, 30));

        SaveAnggota.setText("SAVE");
        SaveAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveAnggotaActionPerformed(evt);
            }
        });
        jPanel3.add(SaveAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 110, 30));

        jLabel17.setFont(new java.awt.Font("Amarillo", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Daftar Anggota Perpustakaan");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 360, 40));

        jPanel8.setBackground(new java.awt.Color(209, 37, 37));
        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 410));

        jTabbedPane1.addTab("Data Anggota", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 68, 730, -1));

        btPrint1.setText("EXIT");
        btPrint1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrint1ActionPerformed(evt);
            }
        });
        getContentPane().add(btPrint1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 520, 110, 30));

        jLabel11.setFont(new java.awt.Font("American Captain", 0, 36)); // NOI18N
        jLabel11.setText("PERPUSTAKAAN TELKOM SCHOOL MALANG");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 730, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrintActionPerformed
        MessageFormat header = new MessageFormat("Data peminjaman buku");
        MessageFormat footer = new MessageFormat("Page {0,number,integer} ");
        try
        {
            tbData.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        }
        catch (java.awt.print.PrinterException e)
        {
            System.err.format("Cannot print %a%n", e.getMessage());
        }
    }//GEN-LAST:event_btPrintActionPerformed

    private void btPrint1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrint1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btPrint1ActionPerformed

    private void btHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHitungActionPerformed
        Date pinjam = Pinjam.getDate();
        Date kembali = Kembali.getDate();
        long startTime = pinjam.getTime();
        long endTime = kembali.getTime();
        long bedaTime = endTime - startTime;
        long bedaHari = bedaTime / (1000 * 60 * 60 * 24);
        DateFormat dateFormat = DateFormat.getDateInstance();

        int lama = toIntExact(bedaHari);
        if (lama > 3)
        {
            int total = lama * 20000;
            String harga = Integer.toString(total);
            Biaya.setText(harga);
        }
        else
        {
            int total = 0;
            String harga = Integer.toString(total);
            Biaya.setText(harga);
        }
        
       
    }//GEN-LAST:event_btHitungActionPerformed

    private void tbDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDataMouseClicked
        int baris = tbData.getSelectedRow();
        if(baris != -1)
        {
            Struk.setText(tbData.getValueAt(baris, 0).toString());
            Judul.setText(tbData.getValueAt(baris, 1).toString());
            Nama.setText(tbData.getValueAt(baris, 2).toString());
            SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
            Date dateFormat = null;
            try
            {
                dateFormat = date.parse(tbData.getValueAt(baris, 3).toString());
            }
            catch (ParseException ex)
            {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            Pinjam.setDate(dateFormat);

            try
            {
                dateFormat = date.parse(tbData.getValueAt(baris, 4).toString());
            }
            catch (ParseException ex)
            {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            Kembali.setDate(dateFormat);
            Biaya.setText(tbData.getValueAt(baris, 5).toString());

        }
    }//GEN-LAST:event_tbDataMouseClicked

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String pinjam = dateFormat.format(Pinjam.getDate());
        String kembali = dateFormat.format(Kembali.getDate());
        Biaya();

        if( Biaya.getText().equals("") || pinjam.equals("") || kembali.equals("") ||
            Nama.getText().equals("") || Judul.getText().equals("") ||
            Struk.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data / Hitung terlebih dahulu !","Error",JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            String SQL = "INSERT INTO tb_pinjam VALUES('"+Struk.getText()+"','"+Nama.getText()
            +"','"+Judul.getText()+"','"+pinjam+"','"+kembali+"','"+Biaya.getText()+"')";
            int status = KoneksiDB.execute(SQL);

            if(status == 1)
            {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan","Sukses",JOptionPane.INFORMATION_MESSAGE);
                selectPinjam();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Data Gagal ditambahkan","Sukses",JOptionPane.WARNING_MESSAGE);
            }

        }
    }//GEN-LAST:event_btSaveActionPerformed

    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        Nama.setText("");
        Struk.setText("");
        Judul.setText("");
        Biaya.setText("");
        Pinjam.setCalendar(null);
        Kembali.setCalendar(null);
    }//GEN-LAST:event_btClearActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        int baris =  tbData.getSelectedRow();
        if (baris != -1)
        {
            String struk = tbData.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_pinjam WHERE Struk='"+struk+"'";
            int status = KoneksiDB.execute(SQL);
            if (status==1)
            {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus","Sukses",JOptionPane.INFORMATION_MESSAGE);
                selectPinjam();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus","Gagal",JOptionPane.WARNING_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih dahulu","Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btDeleteActionPerformed

    private void tbBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbBukuMouseClicked
        // TODO add your handling code here:
        int baris = tbBuku.getSelectedRow();
        if(baris != -1)
        {
            Kode.setText(tbBuku.getValueAt(baris, 0).toString());
            JudulBuku.setText(tbBuku.getValueAt(baris, 1).toString());
            Penulis.setText(tbBuku.getValueAt(baris, 2).toString());
            cbBuku.setSelectedItem(tbBuku.getValueAt(baris, 3).toString());
            Tahun.setText(tbBuku.getValueAt(baris, 4).toString());

        }
    }//GEN-LAST:event_tbBukuMouseClicked

    private void DeleteBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBukuActionPerformed
        // TODO add your handling code here:
        int baris =  tbBuku.getSelectedRow();
        if (baris != -1)
        {
            String kode = tbBuku.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_buku WHERE Kode='"+kode+"'";
            int status = KoneksiDB.execute(SQL);
            if (status==1)
            {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus","Sukses",JOptionPane.INFORMATION_MESSAGE);
                selectBuku();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus","Gagal",JOptionPane.WARNING_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih dahulu","Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_DeleteBukuActionPerformed

    private void PrintBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintBukuActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Data Buku Perpustakaan");
        MessageFormat footer = new MessageFormat("Page {0,number,integer} ");
        try
        {
            tbBuku.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        }
        catch (java.awt.print.PrinterException e)
        {
            System.err.format("Cannot print %a%n", e.getMessage());
        }
    }//GEN-LAST:event_PrintBukuActionPerformed

    private void tbAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAnggotaMouseClicked
        // TODO add your handling code here:
        int baris = tbAnggota.getSelectedRow();
        if(baris != -1)
        {
            Nis.setText(tbAnggota.getValueAt(baris, 0).toString());
            NamaAnggota.setText(tbAnggota.getValueAt(baris, 1).toString());
            Kelas.setText(tbAnggota.getValueAt(baris, 2).toString());
             String JK = tbAnggota.getValueAt(baris, 3).toString();
            if (JK.equals("L"))
                rbLaki.setSelected(true);
            else
                rbPerempuan.setSelected(true);
            Telp.setText(tbAnggota.getValueAt(baris, 4).toString());

        }
    }//GEN-LAST:event_tbAnggotaMouseClicked

    private void PrintAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintAnggotaActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Data Anggota Perpustakaan");
        MessageFormat footer = new MessageFormat("Page {0,number,integer} ");
        try
        {
            tbAnggota.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        }
        catch (java.awt.print.PrinterException e)
        {
            System.err.format("Cannot print %a%n", e.getMessage());
        }
    }//GEN-LAST:event_PrintAnggotaActionPerformed

    private void DeleteAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteAnggotaActionPerformed
        // TODO add your handling code here:
        int baris =  tbAnggota.getSelectedRow();
        if (baris != -1)
        {
            String nis = tbAnggota.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_anggota WHERE Nis='"+nis+"'";
            int status = KoneksiDB.execute(SQL);
            if (status==1)
            {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus","Sukses",JOptionPane.INFORMATION_MESSAGE);
                selectAnggota();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus","Gagal",JOptionPane.WARNING_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih dahulu","Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_DeleteAnggotaActionPerformed

    private void TahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TahunActionPerformed

    private void KodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KodeActionPerformed

    private void JudulBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JudulBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JudulBukuActionPerformed

    private void PenulisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenulisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PenulisActionPerformed

    private void ClearBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBukuActionPerformed
        // TODO add your handling code here:
        Kode.setText("");
        JudulBuku.setText("");
        Tahun.setText("");
        Penulis.setText("");
        cbBuku.setSelectedItem(null);
    }//GEN-LAST:event_ClearBukuActionPerformed

    private void SaveBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBukuActionPerformed
        // TODO add your handling code here:
        
        String kategori = cbBuku.getSelectedItem().toString();

        if( JudulBuku.getText().equals("") || Penulis.getText().equals("") || Tahun.getText().equals("") ||
            kategori.equals("") || Kode.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data!","Error",JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            String SQL = "INSERT INTO tb_buku VALUES('"+Kode.getText()+"','"+JudulBuku.getText()
            +"','"+Penulis.getText()+"','"+kategori+"','"+Tahun.getText()+"')";
            int status = KoneksiDB.execute(SQL);

            if(status == 1)
            {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan","Sukses",JOptionPane.INFORMATION_MESSAGE);
                selectBuku();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Data Gagal ditambahkan","Sukses",JOptionPane.WARNING_MESSAGE);
            }

        }
    }//GEN-LAST:event_SaveBukuActionPerformed

    private void NisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NisActionPerformed

    private void NamaAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaAnggotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaAnggotaActionPerformed

    private void KelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KelasActionPerformed

    private void TelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelpActionPerformed

    private void ClearAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearAnggotaActionPerformed
        // TODO add your handling code here:
        Nis.setText("");
        NamaAnggota.setText("");
        Kelas.setText("");
        Telp.setText("");
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_ClearAnggotaActionPerformed

    private void SaveAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveAnggotaActionPerformed
        // TODO add your handling code here:
         String JK = "";
        if (rbLaki.isSelected())
        {
            JK = "L";   
        }
        if (rbPerempuan.isSelected())
        {
            JK = "P";
        }

        if( Nis.getText().equals("") || NamaAnggota.getText().equals("") || Kelas.getText().equals("") ||
            JK.equals("") || Telp.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data!","Error",JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            String SQL = "INSERT INTO tb_anggota VALUES('"+Nis.getText()+"','"+NamaAnggota.getText()
            +"','"+Kelas.getText()+"','"+JK+"','"+Telp.getText()+"')";
            int status = KoneksiDB.execute(SQL);

            if(status == 1)
            {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan","Sukses",JOptionPane.INFORMATION_MESSAGE);
                selectAnggota();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Data Gagal ditambahkan","Sukses",JOptionPane.WARNING_MESSAGE);
            }

        }
    }//GEN-LAST:event_SaveAnggotaActionPerformed

    private void SearchBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBukuActionPerformed
        // TODO add your handling code here:
        PreparedStatement ps;
        Connection connection;
        String kategori = cbCariBuku.getSelectedItem().toString();
        
        try{connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_perpuspbo?zeroDateTimeBehavior=convertToNull", "root", "");
            String kolom[] = {"KodeBuku","JudulBuku","PenulisBuku","KategoriBuku","TahunBuku"};
            DefaultTableModel dtm = new DefaultTableModel(null,kolom);
            ps = connection.prepareStatement("SELECT `Kode`,`Judul`,`Penulis`,`Kategori`,`Tahun` FROM `tb_buku` "
                + "                         WHERE Kategori = ?");
            ps.setString(1, kategori);
            ResultSet rs = ps.executeQuery();
            try{while(rs.next()){
                String KodeBuku = rs.getString(1);
                String JudulBuku = rs.getString(2);
                String PenulisBuku = rs.getString(3);
                String KategoriBuku = rs.getString(4);
                String TahunBuku = rs.getString(5);
                String data[] = {KodeBuku,JudulBuku,PenulisBuku,KategoriBuku,TahunBuku};
                dtm.addRow(data);   }
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE,null,ex);
        } tbBuku.setModel(dtm);
        } catch (SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Gagal");
        }

    }//GEN-LAST:event_SearchBukuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Biaya;
    private javax.swing.JButton ClearAnggota;
    private javax.swing.JButton ClearBuku;
    private javax.swing.JButton DeleteAnggota;
    private javax.swing.JButton DeleteBuku;
    private javax.swing.JTextField Judul;
    private javax.swing.JTextField JudulBuku;
    private javax.swing.JTextField Kelas;
    private com.toedter.calendar.JDateChooser Kembali;
    private javax.swing.JTextField Kode;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField NamaAnggota;
    private javax.swing.JTextField Nis;
    private javax.swing.JTextField Penulis;
    private com.toedter.calendar.JDateChooser Pinjam;
    private javax.swing.JButton PrintAnggota;
    private javax.swing.JButton PrintBuku;
    private javax.swing.JButton SaveAnggota;
    private javax.swing.JButton SaveBuku;
    private javax.swing.JButton SearchBuku;
    private javax.swing.JTextField Struk;
    private javax.swing.JTextField Tahun;
    private javax.swing.JTextField Telp;
    private javax.swing.JButton btClear;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btHitung;
    private javax.swing.JButton btPrint;
    private javax.swing.JButton btPrint1;
    private javax.swing.JButton btSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbBuku;
    private javax.swing.JComboBox<String> cbCariBuku;
    private javax.swing.JLabel dytk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbPerempuan;
    private javax.swing.JTable tbAnggota;
    private javax.swing.JTable tbBuku;
    private javax.swing.JTable tbData;
    private javax.swing.JLabel vjak;
    // End of variables declaration//GEN-END:variables

    private void selectPinjam() {
        String kolom[] = {"Struk","Nama","Judul","Pinjam","Kembali","Biaya"};
        DefaultTableModel dtm = new DefaultTableModel(null,kolom);
        String SQL = "SELECT * FROM `tb_pinjam`";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try
        {
            while (rs.next())
            {
                
                String Struk = rs.getString(1);
                String Nama = rs.getString(3);
                String Judul = rs.getString(2);
                String Pinjam = rs.getString(4);
                String Kembali = rs.getString(5);
                String Biaya = rs.getString(6);
                String data[] = {Struk,Judul,Nama,Pinjam,Kembali,Biaya};
                dtm.addRow(data);
                        
            }
        }
        catch (SQLException ex)
        {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE,null,ex);
            
        }
        tbData.setModel(dtm);
    }
    
    private void selectBuku() {
        String kolom[] = {"Kode","Judul","Penulis","Kategori","Tahun"};
        DefaultTableModel dtm = new DefaultTableModel(null,kolom);
        String SQL = "SELECT * FROM `tb_buku`";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try
        {
            while (rs.next())
            {
                
                String Kode = rs.getString(1);
                String Judul = rs.getString(2);
                String Penulis = rs.getString(3);
                String Kategori = rs.getString(4);
                String Tahun = rs.getString(5);
                String data[] = {Kode,Judul,Penulis,Kategori,Tahun};
                dtm.addRow(data);
                        
            }
        }
        catch (SQLException ex)
        {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE,null,ex);
            
        }
        tbBuku.setModel(dtm);
    }
    
    private void selectAnggota()
    {
        String kolom[] = {"Nis","Nama","Kelas","JK","Telp"};
        DefaultTableModel dtm = new DefaultTableModel(null,kolom);
        String SQL = "SELECT * FROM `tb_anggota`";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try
        {
            while (rs.next())
            {
                
                String Nis = rs.getString(1);
                String Nama = rs.getString(2);
                String Kelas = rs.getString(3);
                String JK = rs.getString(4);
                String Telp = rs.getString(5);
                String data[] = {Nis,Nama,Kelas,JK,Telp};
                dtm.addRow(data);
                        
            }
        }
        catch (SQLException ex)
        {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE,null,ex);
            
        }
        tbAnggota.setModel(dtm);
    }
    
    public void Biaya()
    {
        Date pinjam = Pinjam.getDate();
        Date kembali = Kembali.getDate();
        long startTime = pinjam.getTime();
        long endTime = kembali.getTime();
        long bedaTime = endTime - startTime;
        long bedaHari = bedaTime / (1000 * 60 * 60 * 24);
        DateFormat dateFormat = DateFormat.getDateInstance();

        int lama = toIntExact(bedaHari);
        if (lama > 3)
        {
            int total = lama * 20000;
            String harga = Integer.toString(total);
            Biaya.setText(harga);
        }
        else
        {
            int total = 0;
            String harga = Integer.toString(total);
            Biaya.setText(harga);
        }
    }
}
